### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by ChialiT** [Blockchain-Powered-eSIM/web#7]
on the landing page, 
github: https://github.com/Blockchain-Powered-eSIM
discord:  https://discord.gg/KfQDsPNn5S

Documentation: docs.kokio.app
@baumstern could you also help to deploy https://github.com/Blockchain-Powered-eSIM/Kokio-docs

**Comment by ChialiT** [comment]
@0xRowdy

**Comment by ChialiT** [comment]
@0xRowdy wrong link on the production:  https://discord.gg/K 
XD

**Comment by 0xRowdy** [comment]
fixed
